services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: shop_nginx
        networks:
            - hotel_network

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: shop_app
        networks:
            - hotel_network
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: hopper.proxy.rlwy.net
            DB_PORT: 19658
            DB_DATABASE: railway
            DB_USERNAME: postgres
            DB_PASSWORD: VyTxsfsryeGezRzFYjqBHWEkgPGRuBJa
            COMPOSER_MEMORY_LIMIT: -1
        ports:
            - "9000:8000"

networks:
    hotel_network:
        driver: bridge
